#!/bin/bash

#Make sure wrapper is suid and others are not readable
chmod 4555 /usr/bin/boca-submit-run-root-wrapper  2>/dev/null
chmod 700 /usr/sbin/boca-fixes 2>/dev/null
chmod 700 /usr/sbin/boca-auth-runs 2>/dev/null
chmod 700 /usr/sbin/boca-outmanage  2>/dev/null
chmod 700 /usr/sbin/boca-submit-log  2>/dev/null
chmod 700 /usr/bin/boca-submit-run-*  2>/dev/null

for i in boca-submit-list boca-submit-oldlist; do
  rm -f /usr/bin/$i || true
  ln -s /usr/bin/boca-submit-run /usr/bin/$i
done
