#!/bin/bash
if [ ! -f /etc/icpc/.isserver ]; then
if [ -x /etc/icpc/bocaserver.sh ]; then
  .	/etc/icpc/bocaserver.sh
fi	   
/sbin/iptables -F INPUT
/sbin/iptables -A INPUT -i lo -j ACCEPT
/sbin/iptables -A INPUT -s 143.107.255.15 -j ACCEPT
if [ "$BOCASERVER" != "" ]; then
  /sbin/iptables -A INPUT -s $BOCASERVER -j ACCEPT
fi
/sbin/iptables -A INPUT -j REJECT
else
	if [ -x /etc/icpc/bocaserver.iptables ]; then
	   . /etc/icpc/bocaserver.iptables
    fi
fi
