#!/bin/bash

if [ "$1" != "" ]; then
	mkdir -p /root/submissions
	chown root /root/submissions
	chmod 700 /root/submissions
	cp "$1" /root/submissions
	echo "date=`date +%s`" >> "/root/submissions/$1"
	echo "code=`cat /root/submissions/code`" >> "/root/submissions/$1"
fi
