#!/bin/bash
if [ "`id bocassh 2>/dev/null`" != "" ]; then
    if [ ! -d /var/www/boca/home/.ssh ]; then
	mkdir -p /var/www/boca/home/.ssh
	chown -R bocassh.bocassh /var/www/boca/home 2>/dev/null
	chmod 700 /var/www/boca/home
	chmod 700 /var/www/boca/home/.ssh
    fi
    for i in 1 2 3 4 5 6; do
	touch /var/www/boca/home/.ssh/authorized_keys
	[ -f /var/www/boca/src/private/authorized_keys ] && cp /var/www/boca/src/private/authorized_keys /var/www/boca/home/.ssh/authorized_keys
	chmod 600 /var/www/boca/home/.ssh/authorized_keys
	[ "$i" == "6" ] || sleep 10
    done
fi
