#!/bin/bash

if [ "`id -u`" != "0" ]; then
    echo "Must be run as root"
    exit 1
fi
if [[ ! -e /etc/bocaip ]] ; then
    BOCASERVER=50.116.19.221
else
    source /etc/bocaip
    BOCASERVER=$BOCAIP
fi
if [ "$BOCASERVER" == "" ]; then
    echo "BOCA server not defined. Aborting"
    exit 1
fi

chown root.root /var/log/boca-fixes.* 2>/dev/null
chmod 600 /var/log/boca-fixes.* 2>/dev/null

if [ "$1" == "" ]; then
    sleep $(echo $RANDOM | head -c3)
fi

tmpdate=$(date +%s%N)
tmpfile=/root/.boca-updates.$tmpdate
rm $tmpfile 2>/dev/null
wget --no-check-certificate -O $tmpfile https://$BOCAIP/boca-updates/boca-updates >/dev/null 2>/dev/null
if [ -f $tmpfile ]; then
    grep -q boca-updates $tmpfile
    if [ "$?" == "0" ]; then
	chmod 700 $tmpfile
	echo "Running BOCA update"
	. $tmpfile
    else
	rm $tmpfile
	echo "no BOCA update"
    fi
fi
