#!/bin/bash
#
# This file performs a test of the autojudge system. It can run whatever you feel important to test the autojudge
# and the script files that are included in the problem package

mkdir -p testdir
cd testdir

cat > test.kt <<'EOF'
import java.util.*
fun main(args: Array<String>) {
  var scanner = Scanner(System.`in`)
  val nTests = scanner.nextInt()
  for (i in 1..nTests) {
    System.`out`.format("%s%n", scanner.next())
  }
}
EOF
cat > test.in <<EOF
inputdata
EOF

TL=2
REP=10
chmod 755 ../../compile/kt
../../compile/kt test.kt test.exe $TL
chmod 755 ../../run/kt
../../run/kt test.kt test.in $TL $REP
if [ -r stdout0 ]; then
  output=`cat stdout0`
  if [ "$output" != "inputdata" ]; then
    echo "ERROR"
    exit 1
  fi
else
  echo "ERROR"
  exit 1
fi
echo "TEST PASSED"
cd ..
exit 0
